server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:mysql://localhost/i4-apparel-user?useSSL=false
    data-username: root
    data-password: nacs
  jpa:
    hibernate:
      ddl-auto: update

admin-user: ADMIN
admin-password: ADMIN