server:
  port: 9011
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      uri: mongodb://localhost/userprofile
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/i4_apparel_user?useSSL=false
#    data-username: root
#    data-password: nacs
#  jpa:
#    hibernate:
#      ddl-auto: update

admin:
  user: ADMIN
  password: ADMIN